# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev3+gbb49181.d20230614"
__version_tuple__ = version_tuple = (0, 1, "dev3", "gbb49181.d20230614")
