# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev6+g6c53f9e.d20230615"
__version_tuple__ = version_tuple = (0, 1, "dev6", "g6c53f9e.d20230615")
